language: java

jdk:
- oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer


install: ./gradlew setupCiWorkspace -S
script: ./gradlew build

env:
  global:
    TERM=dumb
